### PR TITLE
Lesson fixes

### PR DESCRIPTION
**Pull request by powerlanguage**
👋 @btholt, long time! 

I found your course while I was looking to brush up on hooks.  I really like your explanations, so I ended up doing the earlier sections of the course as I figured it'd help me learn some of the areas of React where I am fuzzier.

As I went I made some edits to the lesson markdown files.  Feel free to use/ignore whatever.

- Most of the edits are for typos and clarity
- Some of the code examples were not in sync with the lesson text

### CODE REVIEW

**Comment by 1Marc** [comment]
A bit too large of a PR to easily accept -- will have to go through each line and verify accuracy at some point.

**Comment by 1Marc** [comment]
Regardless, thank you @powerlanguage !

**Comment by powerlanguage** [comment]
@1Marc I can break this up into a PR per file if that'd be easier.

**Comment by 1Marc** [comment]
Closing for now.. breaking it up into smaller commits would make it easier to review especially with lots of other open PRs to review/accept, sorry!

**Pull request closed without merging**
